- name: docker build and push
  hosts: local  # Replace with the hostname or IP address of your target server
  become: yes  # Run tasks with sudo privileges

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes   

    - name: Build Docker Image
      command: docker build -t petjob .
      args:
        chdir: /var/lib/jenkins/workspace/petjob

    - name: tag image
      command: docker tag petjob:latest sundar1586/petjob:latest 

    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: sundar1586
        password: dckr_pat_8vFmap6JS2FoP8QW2WwGjsLm0w4

    - name: Push image
      command: docker push sundar1586/petjob:latest

    - name: Run container
      command: docker run -d --name pet1 -p 8081:8080 sundar1586/petjob:latest
